### ISSUE TITLE
Create a documention site for using jekyll-theme-jakarta-ee

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jekyll-theme-jakarta-ee#11]
With GitHub pages we can serve a website from the /docs folder in the master branch.

I was thinking we could create a small documentation website for this theme within this repo.

I think this would be useful for two reasons:

1. We could write more details instructions for projects who wish to use the theme
2. We could also use this test website to view and make sure that our changes doesn't break the website.

@jgallimore What do you think?

**Comment by chrisguindon** [comment]
Here's a quick start:
https://chrisguindon.github.io/jekyll-theme-jakarta-ee/

I am simply using the content from the README.md for now.

**Comment by jgallimore** [comment]
Great idea, @chrisguindon!

**Comment by chrisguindon** [comment]
The documentation is live and it's available under jakarta.ee domain by default:
https://jakarta.ee/jekyll-theme-jakarta-ee/

Should we take a look at moving this out of jakarta.ee domain?

**Comment by jgallimore** [comment]
Would that require this repository to shift to an outside of the jakartee organization (eclipse-ee4j, maybe)?

I don't have strong views, but it probably makes sense for it to be separate from the main website.

**Comment by chrisguindon** [comment]
I could't find documentation to disable the custom domain for this repo. 

I've sent a support question to github for more information.

**Comment by chrisguindon** [comment]
I just heard back from Github and here's the answer:

Hi Christopher,

Thanks for writing in to GitHub Support and apologies for the delay. We're currently experiencing a high volume of requests, so we appreciate your patience.

When you attach a custom domain to a repository using the username.github.io naming scheme, this custom domain replaces all instances of username.github.io in the URLs for all other Pages sites served from the same account.

To stop this you'll need to rename your jakartaee/jakartaee.github.io to anything else. This will allow this site to continue serving under that custom domain,but the domain won't be inherited to other sites under that account.

Hope this helps! Let us know if you need anything else.

**Comment by chrisguindon** [comment]
jakartaee/jakartaee.github.io has been renamed to jakartaee/jakarta.ee

The documentation site is now available via:
https://jakartaee.github.io/jekyll-theme-jakarta-ee/

Closing this issue!

**Comment by jgallimore** [comment]
Looks good, thanks @chrisguindon !
