### ISSUE TITLE
Release current version of the theme and publish on RubyGems

### ISSUE THREAD

**Issue by jgallimore** [jakartaee/jekyll-theme-jakarta-ee#13]
**Is your feature request related to a problem? Please describe.**
Users need to locally build and install the theme gem in order to use it on their own machine.

**Describe the solution you'd like**
Publish released versions of the theme on Rubygems.org

**Describe alternatives you've considered**
None at present

**Comment by chrisguindon** [comment]
+1

I was thinking we could automatically publish to Rubygems.org via travis-ci each time a new tags is push to the repo:

https://docs.travis-ci.com/user/deployment/rubygems/

**Comment by jgallimore** [comment]
That looks good. We'd want that API key to be encrypted. I think it makes send for the Rubygems account that the gems get uploaded to be owned by the Eclipse Foundation. Are you able to set that up and get the encrypted API key?

**Comment by chrisguindon** [comment]
+1 I will assign this task to me!

I need to figure out a solution so that the version used is the tag to avoid having to change the version in the source code each time. Hopefully the documentation explains how to do that.

**Comment by chrisguindon** [comment]
Quick update:

I am hoping to find some time to look at this next week!

**Comment by chrisguindon** [comment]
The gem is now available on rubygems.org:
https://rubygems.org/gems/jekyll-theme-jakarta-ee

I created #18 to update the instructions for pushing the Gem to RubyGems.

**Comment by chrisguindon** [comment]
The change has been merged!
