### ISSUE TITLE
adjust jekyll theme for Jakarta EE projects pages

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jekyll-theme-jakarta-ee#24]
It would be really helpful if we can adjust jekyll theme for Jakarta EE projects pages to have the same  look and feel as jakarta.ee web page.

**Comment by shabnammayel** [comment]
Also can you please put these pages on Jakarta's domain similar to the start.jakarta.ee? thanks

**Comment by ivargrimstad** [comment]
> Also can you please put these pages on Jakarta's domain similar to the start.jakarta.ee? thanks

We should probably supply a list of the projects where we want DNS entries, what we want the subdomain to be, and the site to point to. I'll start the list in a separate issue...

**Comment by ivargrimstad** [comment]
DNS issue for Helpdesk: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2048

**Comment by chrisguindon** [comment]
@ivargrimstad I posted some info on your issue. This is something that we could manage directly in the Jakarta.ee repo. Updating that file does not require us to involve webmaster.

This is how I configured start.jakarta.ee.

**Comment by chrisguindon** [comment]
I published a new gem version based on the work that @ericpoirier did.

I also did some testing to see how the site would like and I did notice a regression:

- test site: https://chrisguindon.github.io/mail-api/
- prod: https://jakartaee.github.io/mail-api/

The project resource sidebar is missing in the latest revision. 

@ericpoirier Can you please take a look at this? If there is a regression, please ensure to apply it to eclipsefdn theme.

I also think you should reduce the margin between the breadcrumbs and the content section.

**Comment by chrisguindon** [comment]
I took a look and the issue is here:
https://github.com/jakartaee/jekyll-theme-jakarta-ee/commit/6a3d710119a24ff2c6033679878a34d1ff94f57c#diff-907a69846a1f6b238f1c43199984197d12c7eab26f3c3adcd45d628b26644950L33

You removed the sidebar section. We need to bring this back.

**Comment by ericpoirier** [comment]
> I took a look and the issue is here: [6a3d710#diff-907a69846a1f6b238f1c43199984197d12c7eab26f3c3adcd45d628b26644950L33](https://github.com/jakartaee/jekyll-theme-jakarta-ee/commit/6a3d710119a24ff2c6033679878a34d1ff94f57c#diff-907a69846a1f6b238f1c43199984197d12c7eab26f3c3adcd45d628b26644950L33)
> 
> You removed the sidebar section. We need to bring this back.

I created the following PR to add the sidebar back.

https://github.com/jakartaee/jekyll-theme-jakarta-ee/pull/26

**Comment by chrisguindon** [comment]
@TanjaObradovic @ivargrimstad,

I published a new version with the latest fix from @ericpoirier. You can see the update in action here:
https://chrisguindon.github.io/mail-api/

I believe projects need to make an update to the content of the site to trigger GitHub to rebuild with the latest version.
