### ISSUE TITLE
Set up a build environment on Travis-ci

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jekyll-theme-jakarta-ee#3]
It would be nice to have travis-ci build the theme automatically and eventually run tests:
https://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by chrisguindon** [comment]
I created pull request #4 to address this.

It's very simple and basic but it will build the theme with following versions of ruby:
  - 2.1.0
  - 2.2.7
  - 2.3.4
  - 2.4.1

**Comment by chrisguindon** [comment]
An example using my fork:
https://travis-ci.org/chrisguindon/jekyll-theme-jakarta-ee/builds/483195832

**Comment by jgallimore** [comment]
This looks great. Thanks for setting it up @chrisguindon !

**Comment by chrisguindon** [comment]
Thanks @jgallimore 

Closing issue.
